### PR TITLE
Support for fullscreen change events

### PR DESCRIPTION
**Pull request by GomesLuis479**
Added functionality to detect fullscreen change events in the webview containing the youtube iframe.

Creates event listeners to detect fullscreen changes on `document` in the WebView and uses `postMessage` to detect the event along with the fullscreen status (boolean).

Need: This comes after I needed to change the orientation lock in an app that was always locked to portrait by default.

### CODE REVIEW

**Comment by LonelyCpp** [comment]
Hey! 

A fullscreen event is definitely a perfect addition. I'll do some quick tests and merge it if everything checks out. 

Thanks! 😄

**Comment by LonelyCpp** [comment]
Hi @GomesLuis479, sorry for the late responce, I was busy this week. I tested this on android, and it works fine. 

However it doesn't work on an iOS device or simulator.. The `onFullScreenChange` function doesn't fire at all. I'm looking at a few solutions here -  [stackoverflow thread](https://stackoverflow.com/questions/32228024/how-to-detect-ios-leaving-fullscreen-video)

Can you please look into this? Thanks :)

**Comment by LonelyCpp** [comment]
If you do not have access to iOS, let me know

**Comment by GomesLuis479** [comment]
Sorry, But Don't have access  to a Mac or an iPhone. Will read up on the issue and see what I can find.

**Comment by GomesLuis479** [comment]
Added changes as per [stackoverflow thread](https://stackoverflow.com/questions/32228024/how-to-detect-ios-leaving-fullscreen-video).

The fullscreen event listener is now on the `player` element instead of `document`.

Also changed tracking fullscreen status using a variable instead of `document.fullscreenElement` since [this](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/fullscreenElement) (browser compatibility section) mentions that safari on iOS only supports fullscreen on iPad.

Let me know if this works on iOS. Works fine on android.

**Comment by LonelyCpp** [comment]
I'm merging this to a branch since it works well on android. As you dont have access to iOS, I will try to come up with a fix. 

Thanks a ton @GomesLuis479!!

Welcome to the contributor list 🥳

**Comment by rawatmanoj** [comment]
onFullScreenChange still does not works on ios

**Pull request merged**
